name: File 2 - Install 

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Install Mods
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          $mods = @('python', 'notepadplusplus', 'vscode', '7zip', 'git')
          foreach ($mod in $mods) {
              choco install $mod -y --no-progress
          }
